
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.blue;
import static java.awt.Color.green;
import static java.awt.Color.pink;
import static java.awt.Color.red;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Killer
 */
public class TelaPernas extends javax.swing.JFrame {

    /**
     * Creates new form TelaPernas
     */
    public TelaPernas() {
        initComponents();
        lblTipo.setVisible(false);
        lblCobra.setVisible(false);
        lblSaci.setVisible(false);
        lblBipede.setVisible(false);
        lblMiniBoi.setVisible(false);
        lblFormiga.setVisible(false);
        lblMiranha.setVisible(false);
        lblEt.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtPernas = new javax.swing.JSpinner();
        lblCobra = new javax.swing.JLabel();
        lblBipede = new javax.swing.JLabel();
        lblMiniBoi = new javax.swing.JLabel();
        lblFormiga = new javax.swing.JLabel();
        lblMiranha = new javax.swing.JLabel();
        lblEt = new javax.swing.JLabel();
        lblSaci = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        setForeground(java.awt.Color.lightGray);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Quantas Pernas tem o Animal?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Tipo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, -1, -1));

        lblTipo.setFont(new java.awt.Font("Rod", 0, 24)); // NOI18N
        lblTipo.setText("tipo");
        jPanel1.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 59, -1, -1));

        txtPernas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPernas.setModel(new javax.swing.SpinnerNumberModel(-1, null, null, 1));
        txtPernas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtPernasStateChanged(evt);
            }
        });
        jPanel1.add(txtPernas, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 11, 66, -1));

        lblCobra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cobra.jpg"))); // NOI18N
        jPanel1.add(lblCobra, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 113, -1, -1));

        lblBipede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bipede.jpg"))); // NOI18N
        jPanel1.add(lblBipede, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 219, -1, -1));

        lblMiniBoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/miniboi.jpg"))); // NOI18N
        jPanel1.add(lblMiniBoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 219, -1, -1));

        lblFormiga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/formiga.jpg"))); // NOI18N
        jPanel1.add(lblFormiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 325, -1, -1));

        lblMiranha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/miranha.jpg"))); // NOI18N
        jPanel1.add(lblMiranha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, -1, -1));

        lblEt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/et.jpg"))); // NOI18N
        jPanel1.add(lblEt, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 325, -1, -1));

        lblSaci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saci.jpeg"))); // NOI18N
        jPanel1.add(lblSaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 219, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPernasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtPernasStateChanged
        // TODO add your handling code here:
        
        
        
        
        
        int pernas = (int)txtPernas.getValue();
        lblTipo.setVisible(true);
        switch(pernas){
           case 0:
               lblTipo.setForeground(new Color(255, 0, 255));
               lblTipo.setText("COBRA");
               lblCobra.setVisible(true);
               lblSaci.setVisible(false);
               lblBipede.setVisible(false);
               lblMiniBoi.setVisible(false);
               lblFormiga.setVisible(false);
               lblMiranha.setVisible(false);
               lblEt.setVisible(false);
              
               
               
               
           break;
           
           case 1:
               lblTipo.setForeground(black);
               lblTipo.setText("SACI");
               lblCobra.setVisible(false);
               lblSaci.setVisible(true);
               lblBipede.setVisible(false);
               lblMiniBoi.setVisible(false);
               lblFormiga.setVisible(false);
               lblMiranha.setVisible(false);
               lblEt.setVisible(false);
              
           break;
           
           case 2:
               lblTipo.setForeground(blue);
               lblTipo.setText("BIPEDE");
               lblCobra.setVisible(false);
               lblSaci.setVisible(false);
               lblBipede.setVisible(true);
               lblMiniBoi.setVisible(false);
               lblFormiga.setVisible(false);
               lblMiranha.setVisible(false);
               lblEt.setVisible(false);
               
           break;
           
           case 4:
               lblTipo.setForeground(green);
               lblTipo.setText("MINIBOI");
               lblCobra.setVisible(false);
               lblSaci.setVisible(false);
               lblBipede.setVisible(false);
               lblMiniBoi.setVisible(true);
               lblFormiga.setVisible(false);
               lblMiranha.setVisible(false);
               lblEt.setVisible(false);
              
           break;
           
           case 6:
               lblTipo.setForeground(new Color(150, 75, 0));
               lblTipo.setText("FORMIGA");
               lblCobra.setVisible(false);
               lblSaci.setVisible(false);
               lblBipede.setVisible(false);
               lblMiniBoi.setVisible(false);
               lblFormiga.setVisible(true);
               lblMiranha.setVisible(false);
               lblEt.setVisible(false);
               
           break;
           
           case 8:
               lblTipo.setForeground(red);
               lblTipo.setText("MIRANHA");
               lblCobra.setVisible(false);
               lblSaci.setVisible(false);
               lblBipede.setVisible(false);
               lblMiniBoi.setVisible(false);
               lblFormiga.setVisible(false);
               lblMiranha.setVisible(true);
               lblEt.setVisible(false);
               
           break;
           
           default:
               lblTipo.setForeground(new Color(75, 0, 130));
               lblTipo.setText("ET");
               lblCobra.setVisible(false);
               lblSaci.setVisible(false);
               lblBipede.setVisible(false);
               lblMiniBoi.setVisible(false);
               lblFormiga.setVisible(false);
               lblMiranha.setVisible(false);
               lblEt.setVisible(true);
               
           break;
           
       }
        
        
    }//GEN-LAST:event_txtPernasStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPernas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPernas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPernas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPernas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPernas().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBipede;
    private javax.swing.JLabel lblCobra;
    private javax.swing.JLabel lblEt;
    private javax.swing.JLabel lblFormiga;
    private javax.swing.JLabel lblMiniBoi;
    private javax.swing.JLabel lblMiranha;
    private javax.swing.JLabel lblSaci;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JSpinner txtPernas;
    // End of variables declaration//GEN-END:variables
}
